<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2019-02-09
 * Time: 16:48
 */


?>
<section>
    <nav>
        <ul>
            <li>
                <a href="../ksiegarnia">Księgarnia</a>
            </li>
            <li>
                <a href="ksiegarnia/add">Dodaj książkę</a>
            </li>
            <li>
                <a href="ksiegarnia/edit">Edytuj książki</a>
            </li>
        </ul>
    </nav>
</section>
<div class="row">
    <div class="col-lg-6">
        <form>
            <div class="form-group">
                <label for="titleBooks">Tytuł książki</label>
                <input type="text" class="form-control" id="titleBooks" aria-describedby="" placeholder="Tytuł książki">
            </div>
            <div class="form-group">
                <label for="authorBooks">Autor książki</label>
                <input type="text" class="form-control" id="authorBooks" aria-describedby="" placeholder="Autor książki">
            </div>
            <div class="form-group">
                <label for="descriptionBooks">Opis książki</label>
                <textarea class="form-control" id="descriptionBooks" aria-describedby="" placeholder="Opis książki"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Zapisz książkę</button>
        </form>
    </div>
</div>
