<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2019-02-09
 * Time: 16:48
 */


?>

<section>
    <nav>
        <ul>
            <li>
                <a href="../user">Użytkownik</a>
            </li>
            <li>
                <a href="../user/add">Dodaj użytkownika</a>
            </li>
            <li>
                <a href="user/edit">Edytuj użytkownika</a>
            </li>
        </ul>
    </nav>
</section>
<div class="row">
    <div class="col-lg-6">
        <form>
            <div class="form-group">
                <label for="loginUser">Nazwa użytkownika</label>
                <input type="text" class="form-control" id="loginUser" aria-describedby="" placeholder="Nazwa użytkownika">
            </div>
            <div class="form-group">
                <label for="emailAdress">Podaj adres email</label>
                <input type="email" class="form-control" id="emailAdress" aria-describedby="" placeholder="">
            </div>
            <div class="form-group">
                <label for="city">Podaj nazwę miasta</label>
                <input type="email" class="form-control" id="city" aria-describedby="" placeholder="">
            </div>
            <div class="form-group">
                <label for="street">Podaj ulicę</label>
                <input type="text" class="form-control" id="street" aria-describedby="" placeholder="">
            </div>
            <div class="form-group">
                <label for="numberHouse">Podaj nr domu</label>
                <input type="text" class="form-control" id="numberHouse" aria-describedby="" placeholder="">
            </div>
            <div class="form-group">
                <label for="phoneNumber">Podaj nr telefonu</label>
                <input type="text" class="form-control" id="phoneNumber" aria-describedby="" placeholder="">
            </div>
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </form>
    </div>
</div>

